### PR TITLE
Add channel state diagram

### LINKED ISSUE #50: Add channel state diagrams
We at least need a channel state diagram for client, and probably also for server.
(like https://www.rfc-editor.org/rfc/rfc9000#fig-stream-send-states and https://www.rfc-editor.org/rfc/rfc9000#fig-stream-recv-states and https://www.ietf.org/archive/id/draft-ietf-quic-multipath-01.html#fig-path-states)

### PR DESCRIPTION
**Pull request by MaxF12**
Only from the client point of view for now, I think server side might not actually be necessary because its very similar? (Basically just switch send/receive in front of the frames I think) 

Closes #50

### CODE REVIEW

**Comment by MaxF12** [comment]
I guess a question would be where "declined join" goes, does it just return to unjoined or does it retire the channel (probably not)?

**Comment by MaxF12** [comment]
I also didn't include "Held down" as a state since I didn't see what interaction would make it transition back to "unjoined", so it seemed redundant

**Review by GrumpyOldTroll — APPROVED** [review]
This is really good, thanks.

I think I'd probably rather call "attempting joined" -> "joined" and "joined" -> "confirmed" or something, but this is really good.

Also, I do think we need a similar one for server, the state transitions are from different events I think.

**Comment by MaxF12** [comment]
Only have two states, joined and unjoined, remove timeout triggers, have transition from unjoined to unjoined after receiving a leave

**Comment by MaxF12** [comment]
On thinking about it more, didn't add the reflexive arrow for unjoined since the same would also be required for joined when a join arrives and initialized when both join or leave arrive. I think that would make the diagram unnecessarily crowded, this way only action that actually lead to a state change are pictured which I think is consistent. 

Also added text to deal with retiring a channel better since it feels relevant to the diagram (closes #58)

**Pull request merged**
